config/routes.rb
Rails.application.routes.draw do
  resources :card_partnerships
  resources :loyalty_programs
  resources :airlines
  resources :cards
  resources :calculations do
    collection do
      get "optimize"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/loyalty_program.rb
class LoyaltyProgram < ApplicationRecord
  has_many :card_partnerships
  has_many :cards, through: :card_partnerships
end

app/controllers/loyalty_programs_controller.rb
class LoyaltyProgramsController < ApplicationController
  before_action :set_loyalty_program, only: %i[ show edit update destroy ]

  # GET /loyalty_programs or /loyalty_programs.json
  def index
    @loyalty_programs = LoyaltyProgram.all
  end

  # GET /loyalty_programs/1 or /loyalty_programs/1.json
  def show
  end

  # GET /loyalty_programs/new
  def new
    @loyalty_program = LoyaltyProgram.new
  end

  # GET /loyalty_programs/1/edit
  def edit
  end

  # POST /loyalty_programs or /loyalty_programs.json
  def create
    @loyalty_program = LoyaltyProgram.new(loyalty_program_params)

    respond_to do |format|
      if @loyalty_program.save
        format.html { redirect_to loyalty_program_url(@loyalty_program), notice: "Loyalty program was successfully created." }
        format.json { render :show, status: :created, location: @loyalty_program }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loyalty_program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loyalty_programs/1 or /loyalty_programs/1.json
  def update
    respond_to do |format|
      if @loyalty_program.update(loyalty_program_params)
        format.html { redirect_to loyalty_program_url(@loyalty_program), notice: "Loyalty program was successfully updated." }
        format.json { render :show, status: :ok, location: @loyalty_program }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loyalty_program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loyalty_programs/1 or /loyalty_programs/1.json
  def destroy
    @loyalty_program.destroy!

    respond_to do |format|
      format.html { redirect_to loyalty_programs_url, notice: "Loyalty program was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loyalty_program
      @loyalty_program = LoyaltyProgram.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loyalty_program_params
      params.require(:loyalty_program).permit(:name, :category)
    end
end

app/helpers/loyalty_programs_helper.rb
module LoyaltyProgramsHelper
end

app/views/loyalty_programs/_form.html.erb
<%= form_with(model: loyalty_program, class: "contents") do |form| %>
  <% if loyalty_program.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(loyalty_program.errors.count, "error") %> prohibited this loyalty_program from being saved:</h2>

      <ul>
        <% loyalty_program.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category %>
    <%= form.text_field :category, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/loyalty_programs/_loyalty_program.html.erb
<div id="<%= dom_id loyalty_program %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= loyalty_program.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= loyalty_program.category %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Partners:</strong>
    <% loyalty_program.card_partnerships.each do |partnership| %>
      <%= partnership.card.name %>
    <% end %>
  </p>


</div>

app/views/loyalty_programs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing loyalty program</h1>

  <%= render "form", loyalty_program: @loyalty_program %>

  <%= link_to "Add partnership", new_card_partnership_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to loyalty programs", loyalty_programs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/loyalty_programs/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Loyalty programs" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Loyalty programs</h1>
    <%= link_to "New loyalty program", new_loyalty_program_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="loyalty_programs" class="min-w-full">
    <% @loyalty_programs.each do |loyalty_program| %>
      <%= render loyalty_program %>
      <p>
        <%= link_to "Show this loyalty program", loyalty_program, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/loyalty_programs/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New loyalty program</h1>

  <%= render "form", loyalty_program: @loyalty_program %>

  <%= link_to "Back to loyalty programs", loyalty_programs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/loyalty_programs/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @loyalty_program %>

    <%= link_to "Edit this loyalty program", edit_loyalty_program_path(@loyalty_program), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to loyalty programs", loyalty_programs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this loyalty program", @loyalty_program, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>