config/routes.rb
Rails.application.routes.draw do
  resources :card_partnerships
  resources :loyalty_programs
  resources :airlines
  resources :cards
  resources :calculations do
    collection do
      get "optimize"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :card_partnerships
  has_many :loyalty_programs, through: :card_partnerships
  def value
    points * conversion_rate / 100
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to card_url(@card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy!

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:name, :points, :value, :conversion_rate)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div id="<%= dom_id card %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= card.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Points:</strong>
    <%= card.points %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Value:</strong>
    <%= "$%0.2f" % [card.value] %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Conversion:</strong>
    <%= card.conversion_rate %>
  </p>

</div>

app/views/cards/_card_row.html.erb
<div id="<%= dom_id card %>" class="contents">
  <p class="my-5">
    <%= card.name %>
  </p>

  <p class="my-5">
    <%= card.points %>
  </p>

  <p class="my-5">
    <%= "$%0.2f" % [card.value] %>
  </p>

  <p class="my-5">
    <%= card.conversion_rate %>
  </p>

  <p class="my-5">
    <% card.card_partnerships.each do |partnership| %>
      <%= partnership.loyalty_program.name %>
    <% end %>
  </p>

</div>

app/views/cards/_form.html.erb
<%= form_with(model: card, class: "contents") do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :points %>
    <%= form.number_field :points, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%# <div class="my-5">
    <%= form.label :value %>
    <%# <%= form.text_field :value, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  <%# </div> %>

  <div class="my-5">
    <%= form.label :conversion_rate %>
    <%= form.text_field :conversion_rate, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing card</h1>

  <%= render "form", card: @card %>
  
  <%= link_to "Add partnership", new_card_partnership_path,class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to cards", cards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cards/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Cards" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Cards</h1>
    <%= link_to "New card", new_card_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="cards" class="min-w-full grid grid-cols-6">
      <p>Name</p>
      <p>Points</p>
      <p>Value</p>
      <p>Conversion</p>
      <p>Partners</p>
       <p>Show</p>
    <% @cards.each do |card| %>
      <%= render "card_row", card: card %>
      <p>
        <%= link_to "Show this card", card, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/cards/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New card</h1>

  <%= render "form", card: @card %>

  <%= link_to "Back to cards", cards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cards/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @card %>

    <%= link_to "Edit this card", edit_card_path(@card), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to cards", cards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this card", @card, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>