config/routes.rb
Rails.application.routes.draw do
  resources :card_partnerships
  resources :loyalty_programs
  resources :airlines
  resources :cards
  resources :calculations do
    collection do
      get "optimize"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/card_partnership.rb
class CardPartnership < ApplicationRecord
  belongs_to :card
  belongs_to :loyalty_program
end

app/controllers/card_partnerships_controller.rb
class CardPartnershipsController < ApplicationController
  before_action :set_card_partnership, only: %i[ show edit update destroy ]

  # GET /card_partnerships or /card_partnerships.json
  def index
    @card_partnerships = CardPartnership.all
  end

  # GET /card_partnerships/1 or /card_partnerships/1.json
  def show
  end

  # GET /card_partnerships/new
  def new
    @card_partnership = CardPartnership.new
  end

  # GET /card_partnerships/1/edit
  def edit
  end

  # POST /card_partnerships or /card_partnerships.json
  def create
    @card_partnership = CardPartnership.new(card_partnership_params)

    respond_to do |format|
      if @card_partnership.save
        format.html { redirect_to card_partnership_url(@card_partnership), notice: "Card partnership was successfully created." }
        format.json { render :show, status: :created, location: @card_partnership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card_partnership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /card_partnerships/1 or /card_partnerships/1.json
  def update
    respond_to do |format|
      if @card_partnership.update(card_partnership_params)
        format.html { redirect_to card_partnership_url(@card_partnership), notice: "Card partnership was successfully updated." }
        format.json { render :show, status: :ok, location: @card_partnership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card_partnership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /card_partnerships/1 or /card_partnerships/1.json
  def destroy
    @card_partnership.destroy!

    respond_to do |format|
      format.html { redirect_to card_partnerships_url, notice: "Card partnership was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card_partnership
      @card_partnership = CardPartnership.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_partnership_params
      params.require(:card_partnership).permit(:card_id, :loyalty_program_id, :conversion_rate, :notes)
    end
end

app/helpers/card_partnerships_helper.rb
module CardPartnershipsHelper
end

app/views/card_partnerships/_card_partnership.html.erb
<div id="<%= dom_id card_partnership %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Card:</strong>
    <%= card_partnership.card.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Loyalty program:</strong>
    <%= card_partnership.loyalty_program.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Conversion rate:</strong>
    <%= card_partnership.conversion_rate %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Notes:</strong>
    <%= card_partnership.notes %>
  </p>

</div>

app/views/card_partnerships/_form.html.erb
<%= form_with(model: card_partnership, class: "contents") do |form| %>
  <% if card_partnership.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(card_partnership.errors.count, "error") %> prohibited this card_partnership from being saved:</h2>

      <ul>
        <% card_partnership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :card_id %>
    <%# <%= form.number_field :card_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %> 
    <%= form.collection_select(:card_id, Card.all, :id, :name) %>
  </div>

  <div class="my-5">
    <%= form.label :loyalty_program_id %>
    <%# <%= form.number_field :loyalty_program_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %> 
    <%= form.collection_select(:loyalty_program_id, LoyaltyProgram.all, :id, :name) %>
  </div>

  <div class="my-5">
    <%= form.label :conversion_rate %>
    <%= form.text_field :conversion_rate, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :notes %>
    <%= form.text_field :notes, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/card_partnerships/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing card partnership</h1>

  <%= render "form", card_partnership: @card_partnership %>

  <%= link_to "Show this card partnership", @card_partnership, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to card partnerships", card_partnerships_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/card_partnerships/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Card partnerships" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Card partnerships</h1>
    <%= link_to "New card partnership", new_card_partnership_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="card_partnerships" class="min-w-full">
    <% @card_partnerships.each do |card_partnership| %>
      <%= render card_partnership %>
      <p>
        <%= link_to "Show this card partnership", card_partnership, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/card_partnerships/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New card partnership</h1>

  <%= render "form", card_partnership: @card_partnership %>

  <%= link_to "Back to card partnerships", card_partnerships_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/card_partnerships/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @card_partnership %>

    <%= link_to "Edit this card partnership", edit_card_partnership_path(@card_partnership), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to card partnerships", card_partnerships_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this card partnership", @card_partnership, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>